const shops = [
  {
    url: "boulangerie-du-vieux-tours.fr",
    name: "Boulangerie du Vieux-Tours",
    nav: ["Accueil", "Nos pains", "Contact"],
    title: "Pain au levain, cuit au feu de bois.",
    lead: "Boulangerie artisanale, place du Grand Marché à Tours.",
    cards: ["Pains au levain", "Viennoiseries", "Commande la veille"],
    hours: [
      ["Mar – Ven", "6 h 30 – 19 h 30"],
      ["Samedi", "7 h – 19 h"],
      ["Dimanche", "7 h – 13 h"],
    ],
    addr: ["12 place du Grand Marché", "37000 Tours"],
    call: "Appeler la boutique",
    phone: "02 47 00 00 00",
    avis: "4,8 ★ · 126 avis Google",
    type: "Boulangerie artisanale · Tours",
    promo: "-20 % sur les viennoiseries, cette semaine seulement !",
  },
  {
    url: "salon-camille-tours.fr",
    name: "Salon Camille",
    nav: ["Accueil", "Prestations", "Contact"],
    title: "Coupe, couleur, sur rendez-vous.",
    lead: "Salon de coiffure, quartier des Halles à Tours.",
    cards: ["Coupe & brushing", "Couleur végétale", "Rendez-vous en ligne"],
    hours: [
      ["Mar – Ven", "9 h – 19 h"],
      ["Samedi", "9 h – 18 h"],
      ["Lundi", "Fermé"],
    ],
    addr: ["8 rue Bernard Palissy", "37000 Tours"],
    call: "Prendre rendez-vous",
    phone: "02 47 00 00 00",
    avis: "4,9 ★ · 84 avis Google",
    type: "Salon de coiffure · Tours",
    promo: "Offre decouverte : -30 % sur votre premiere couleur !",
  },
  {
    url: "atelier-fleuri-tours.fr",
    name: "Atelier Fleuri",
    nav: ["Accueil", "Nos bouquets", "Contact"],
    title: "Bouquets du jour, fleurs de saison.",
    lead: "Fleuriste, avenue de Grammont à Tours.",
    cards: ["Bouquets du jour", "Mariages & événements", "Livraison à Tours"],
    hours: [
      ["Mar – Sam", "9 h – 19 h 30"],
      ["Dimanche", "9 h – 13 h"],
      ["Lundi", "Fermé"],
    ],
    addr: ["145 avenue de Grammont", "37000 Tours"],
    call: "Commander un bouquet",
    phone: "02 47 00 00 00",
    avis: "4,7 ★ · 203 avis Google",
    type: "Fleuriste · Tours",
    promo: "Livraison offerte des 39 € — cette semaine !",
  },
];

export const JUNK = {
  marquee:
    "★ ★ ★ BIENVENUE SUR NOTRE SITE INTERNET ★ NOUVEAU ★ PENSEZ A AJOUTER AUX FAVORIS ★ ★ ★",
  carousel: "Diaporama automatique · 1 / 6",
  ad: "EMPLACEMENT PUBLICITAIRE",
  counter: "Vous etes le 000247eme visiteur !",
  works: "SITE EN CONSTRUCTION",
  chat: "Besoin d'aide ? Cliquez ici !",
  popup: "INSCRIVEZ-VOUS A NOTRE NEWSLETTER !!!",
  popupButton: "JE M'INSCRIS",
  cookie: "Ce site utilise des cookies pour ameliorer votre experience.",
  cookieButton: "TOUT ACCEPTER",
  extraNav: ["Galerie", "Livre d'or", "Liens"],
  itinerary: "Itinéraire",
  hoursLabel: "HORAIRES",
  addrLabel: "OÙ NOUS TROUVER",
};

export default shops;
